# Site settings
title: 不说
email: yanbo.wu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  各种胡思乱想，胡说八道。
  不代表本人任职公司观点，也不代表本人观点。
baseurl: ""
#url: "http://blog.wuyb.com"
production_url : http://wuyb.github.io
twitter_username: wuyanbo
github_username:  wuyb
encoding: utf-8

# Build settings
markdown: kramdown
